services:
  mariadb:
    image: docker.io/mariadb:11.2
    container_name: travel-map-mariadb
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-travel_map}
      MYSQL_USER: ${MYSQL_USER:-travel_map}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-secret}
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3
  adminer:
      image: docker.io/adminer:4.8.1
      restart: unless-stopped
      ports:
        - 8080:8080
volumes:
  mariadb_data:
    driver: local
